/**
 * Land-Wasser-Maske der Erde für den gepunkteten Globus.
 *
 * 360 × 180 Zellen (ein Grad je Zelle), ein Bit je Zelle, Base64 gepackt —
 * 8100 Byte. Die Maske liegt bewusst als Literal im Quelltext: der Globus soll
 * ohne Netzabruf und ohne zusätzliches Paket auskommen.
 *
 * Erzeugt aus grob nachgezeichneten Küstenlinien. Genau genug, dass die
 * Kontinente in einem Punktraster wiedererkennbar sind — mehr braucht es bei
 * rund vier Grad Punktabstand nicht. Zeile 0 liegt bei 90° N, Spalte 0 bei
 * 180° W, jede Zelle wird über ihre Mitte gelesen.
 */

const COLUMNS = 360;
const ROWS = 180;

// prettier-ignore
const PACKED = `
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/AB////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAP//7//////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//////////+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAH///////////wAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////////gAAAB/8AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAB8B/////////gAAAB/gAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/////////AAAAAAAAAAAAAAAAAAB/8AAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAAAAAAAAAAAP///AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/////4AAAAAAAAAAAAAAAAA////wAAAAAAAAAAA
AAAAAAAAAfwAAAAAH4AAH/////4AAAAAAAAAAAABAAAB////+AAAAAAAAAAAAAAAAAAAAfgAAAAAP/AAH/////wAAAAAAAAAAAAEAB8////////4AIAAAAAA
AAAAAAAAAAP8AAAA//wAD/////wAAAAAAAAAAAAgAH////////////gAAAAAAAAP/AAAAAP/AAAB//+AB/////wAAAAAAB+AAAAAAP//////////////wAAA
AAB//////gD/4AAB///wA////4AAAAAAAf/gAAAAAf////////////////+AAAP///////wAABwB///8Af//8AAAAAAAD///AwA/////////////////////
/Af///////////4A///4AP//wAAAAAAAH///8f///////////////////////4////////////8A///wAH//AAAAAAAAP//8Y///////////////////////
/8////////////4AP//AAH/8AAf4AAAA/8/+A////////////////////////gH///////////gAH/8AAD/4AAf8AAAB/5//h///////////////////////
8AB///////////wAD/gAAD/wAABAAAAB/j//////////////////////////AAH///////////wAAAAAAB/gAAAAAAA//D//////////////////////////
AAH///////////wAA/AAAAfAAAAAAAA//D//////////////////////wf/wAAH///////////wAA//AAAOAAAAAAAB//Af////////////////////8B/8A
AAB//gB///////wAA//gAAAAAAAAAAB9/AP////////////////////gPgAAAAAf8AAP//////wAA//gAAAAAAAAAIAw/A///////////////////8AAfwAA
AAAPwAAD//////4AA//4AAAAAAAAA8AG+B///////////////////wAA/gAAAAAGAAAB///////gA//wAAAAAAAAA8AM8H///////////////////gAA/AAA
AAAAAAAA///////8B//4AAAAAAAAAeAMAH///////////////////gAA+AAAAAAAAAAAf///////x//+AAAAAAAAHOAOAf///////////////////wAA8AAA
AAAAAAAAP///////x///4AAAAAAAPPAf/////////////////////yAA4AAAAAAAAAAAH///////5///8AAAAAAAPfz//////////////////////6AAwAAA
AAAAAAAAD///////////+AAAAAAAAPj//////////////////////6AAAAAAAAAAAAAAB//////////8GAAAAAAAAYf//////////////////////yAAAAAA
AAAAAAAAA/////////+APAAAAAAAAD///////////////////////yAAAAAAAAAAAAAAAf////////7wfgAAAAAAAf///////////////////////yAAAAAA
AAAAAAAAAP/////////wfgAAAAAAAH///////////////////////iAAAAAAAAAAAAAAAP/////////wAAAAAAAAAB//////3/f//////////////AAAAAAA
AAAAAAAAAP/////////+AAAAAAAAAB//v/++P/B/////////////+AAAAAAAAAAAAAAAAP////////8AAAAAAAAAAD//n/8ef+B/////////////4HgAAAAA
AAAAAAAAAP////////4AAAAAAAAABz/Dz/8AD/h/////////////gPgAAAAAAAAAAAAAAP////////wAAAAAAAAAH/4B4/8AB/w////////////8APAAAAAA
AAAAAAAAAP////////gAAAAAAAAAH/wAcf8///w////////////8AAAAAAAAAAAAAAAAAP///////8AAAAAAAAAAH/gAPOP///4////////////8AIAAAAAA
AAAAAAAAAP///////4AAAAAAAAAAH/AAGOP///x///////////58AMAAAAAAAAAAAAAAAH///////4AAAAAAAAAAH+AAEGH///h//////////8A8AYAAAAAA
AAAAAAAAAD///////wAAAAAAAAAAH+AAAHH///g//////////+A8A4AAAAAAAAAAAAAAAD///////wAAAAAAAAAAAwP+AAAA//////////////g4B4AAAAAA
AAAAAAAAAB///////wAAAAAAAAAAA//+AAAA//////////////A4/wAAAAAAAAAAAAAAAA///////gAAAAAAAAAAB//+AAAA/////////////+AB+AAAAAAA
AAAAAAAAAAP/////+AAAAAAAAAAAD///AAAB//////////////ADwAAAAAAAAAAAAAAAAAH/////+AAAAAAAAAAAD///4CAB//////////////gDAAAAAAAA
AAAAAAAAAAC/////8AAAAAAAAAAAH///8PwD//////////////wDAAAAAAAAAAAAAAAAAAAf////8AAAAAAAAAAAP//////3//////////////wAAAAAAAAA
AAAAAAAAAABP///44AAAAAAAAAAAP/////////P///////////gAAAAAAAAAAAAAAAAAAAAn//gAYAAAAAAAAAAAf//////7//j///////////gAAAAAAAAA
AAAAAAAAAAAX//AAYAAAAAAAAAAB///////8//gf//////////AAAAAAAAAAAAAAAAAAAAAD/+AAMAAAAAAAAAAD///////8//wD//////////AAAAAAAAAA
AAAAAAAAAAAJ/+AAIAAAAAAAAAAD///////+f/8A/////////+AAAAAAAAAAAAAAAAAAAAAE/8AAAAAAAAAAAAAH///////+P//8Af///////8QAAAAAAAAA
AAAAAAAAAAAAf8AAAAAAAAAAAAAP////////P//+AH///////wwAAAAAAAAAAAAAAAAAAAAAP8AA+AAAAAAAAAAP////////n//+AH///////gAAAAAAAAAA
AAAAAAAAAAAAP+AAHgAAAAAAAAAP////////n//+AD//4P//YAAAAAAAAAAAAAAAAAAAAAAAH+A4AYAAAAAAAAAP////////j//+AAf/wH/+AAAAAAAAAAAA
AAAAAAAAAAAAH/B4ADwAAAAAAAAP////////h//4AAf/wH/+AAAAAAAAAAAAAAAAAAAAAAAAB/jwAD4AAAAAAAAP////////x//wAAf/AD/+AAAAAAAAAAAA
AAAAAAAAAAAAAf/wAAAAAAAAAAAP////////4//gAAf+AD//AAwAAAAAAAAAAAAAAAAAAAAAAB/4AAAAAAAAAAAf////////4f+AAAP+AB//AAwAAAAAAAAA
AAAAAAAAAAAAAAP+AAAAAAAAAAAf////////8f8AAAP8AAf/AA4AAAAAAAAAAAAAAAAAAAAAAAH/gAAAAAAAAAAf////////+fgAAAP4AAP/gAcAAAAAAAAA
AAAAAAAAAAAAAAA/gAAAAAAAAAAf/////////eAAAAH4AAP/gAYAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAf/////////gAAAAHwAAN/gAAAAAAAAAAA
AAAAAAAAAAAAAAAHgD4AAAAAAAAP/////////gIAAAHwAAM/AAAAAAAAAAAAAAAAAAAAAAAAAAADgH/8AAAAAAAH//////////4AAADwAAMeAAAAAAAAAAAA
AAAAAAAAAAAAAAABgP/+AAAAAAAD//////////4AAABgAAMMAABAAAAAAAAAAAAAAAAAAAAAAAAAf///AAAAAAAB//////////wAAABIAAOAAADAAAAAAAAA
AAAAAAAAAAAAAAAAAf//gAAAAAAAf/////////gAAAAMAAGAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAf//4AAAAAAAP/////////gAAAAIAAGAAAPAAAAAAAAA
AAAAAAAAAAAAAAAAAf///AAAAAAAH/D///////AAAAAAABDAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAf///wAAAAAACAB//////+AAAAAAAAxAAGAAAAAAAAAA
AAAAAAAAAAAAAAAAA////4AAAAAAAAAD/////8AAAAAAAA4gA8AAAAAAAAAAAAAAAAAAAAAAAAAAA////4AAAAAAAAAD/////8AAAAAAAAcAH8AAAAAAAAAA
AAAAAAAAAAAAAAAAB////4AAAAAAAAAD/////4AAAAAAAAeAP4AAAAAAAAAAAAAAAAAAAAAAAAAAD////8AAAAAAAAAH/////wAAAAAAAAPAf58AAAAAAAAA
AAAAAAAAAAAAAAAAD////8AAAAAAAAAH/////AAAAAAAAAPwf4wAAAAAAAAAAAAAAAAAAAAAAAAAH////+AAAAAAAAAD/////AAAAAAAAAHwfxAB+AAAAAAA
AAAAAAAAAAAAAAAAH/////8AAAAAAAAB////+AAAAAAAAADwPhgA/wAAAAAAAAAAAAAAAAAAAAAAH//////4AAAAAAAA////8AAAAAAAAAB4ABgAf+AAAAAA
AAAAAAAAAAAAAAAAH//////+AAAAAAAA////8AAAAAAAAAAYABgAP/gAAAAAAAAAAAAAAAAAAAAAH///////AAAAAAAA////4AAAAAAAAAAMABAAH/4AAAAA
AAAAAAAAAAAAAAAAD///////gAAAAAAA////4AAAAAAAAAAHwAAAD/8AAAAAAAAAAAAAAAAAAAAAB///////gAAAAAAAf///4AAAAAAAAAAB+AAAA/+AAAAA
AAAAAAAAAAAAAAAAB///////gAAAAAAAf///8AAAAAAAAAAAAAAAAP/AAAAAAAAAAAAAAAAAAAAAA///////AAAAAAAAf///8AAAAAAAAAAAAAAAAABAAAAA
AAAAAAAAAAAAAAAAA//////+AAAAAAAAf///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/////+AAAAAAAAf///8AAAAAAAAAAAAAAAACAAAAAA
AAAAAAAAAAAAAAAAAf/////8AAAAAAAAf///8AAAAAAAAAAAAAAB+CAAAAAAAAAAAAAAAAAAAAAAAP/////4AAAAAAAA////8AwAAAAAAAAAAAAD+CAAAAAA
AAAAAAAAAAAAAAAAAP/////4AAAAAAAA////8BwAAAAAAAAAAABH+DAAAAAAAAAAAAAAAAAAAAAAAD/////4AAAAAAAA////8DwAAAAAAAAAAAD/+HgAAAAA
AAAAAAAAAAAAAAAAAB/////4AAAAAAAA////4DwAAAAAAAAAAAD//PgAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAA////wHwAAAAAAAAAAAH///wAAAAA
AAAAAAAAAAAAAAAAAAP////wAAAAAAAA////AHgAAAAAAAAAAAf///wAAAAAAAAAAAAAAAAAAAAAAAP////wAAAAAAAAf//+APgAAAAAAAAAAA////4AAAAA
AAAAAAAAAAAAAAAAAAP////gAAAAAAAAf//+APgAAAAAAAAAAD////8AAAAAAAAAAAAAAAAAAAAAAAP////AAAAAAAAAP//+AfAAAAAAAAAAAf////+AAAAA
AAAAAAAAAAAAAAAAAAP///+AAAAAAAAAP//+APAAAAAAAAAAA//////AAAAAAAAAAAAAAAAAAAAAAAP///4AAAAAAAAAH//+APAAAAAAAAAAA//////gAAAA
AAAAAAAAAAAAAAAAAAf///gAAAAAAAAAH//+AOAAAAAAAAAAA//////wAAAAAAAAAAAAAAAAAAAAAAf///gAAAAAAAAAH//4AEAAAAAAAAAAA//////4AAAA
AAAAAAAAAAAAAAAAAAf///AAAAAAAAAAH//wAAAAAAAAAAAAA//////4AAAAAAAAAAAAAAAAAAAAAAf///AAAAAAAAAAD//wAAAAAAAAAAAAA//////4AAAA
AAAAAAAAAAAAAAAAAAf//+AAAAAAAAAAD//wAAAAAAAAAAAAA//////4AAAAAAAAAAAAAAAAAAAAAAf//8AAAAAAAAAAB//gAAAAAAAAAAAAAf/////4AAAA
AAAAAAAAAAAAAAAAAAf//4AAAAAAAAAAB//AAAAAAAAAAAAAAf/////wAAAAAAAAAAAAAAAAAAAAAAf//wAAAAAAAAAAA/+AAAAAAAAAAAAAAP/////wAAAA
AAAAAAAAAAAAAAAAAA///gAAAAAAAAAAA/8AAAAAAAAAAAAAAP/AP//wAAAAAAAAAAAAAAAAAAAAAA///AAAAAAAAAAAA/wAAAAAAAAAAAAAAf4AD//gAAAA
AAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAcAAAAAAAAAAAAAAAPAAB//gAAAAAAAAAAAAAAAAAAAAAB//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAABA
AAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAAgAAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+AAAA8
AAAAAAAAAAAAAAAAAB//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4
AAAAAAAAAAAAAAAAAD/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAD/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAADA
AAAAAAAAAAAAAAAAAD/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAHAAAAAAAAAAAAAAAAAAD/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAeA
AAAAAAAAAAAAAAAAAH/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAAAAAAAAAH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4A
AAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAB/8AAAAAAAAAAAAAAAAAAAAAAAA//////8AAAAAAAAAAAAAAAAAAAAAAAAAAH//AAAAAAAAAAAAAAAAD//////////////8AAAAAAA
AAAAAAAAAAAAAAAAAA///gAAAAAAAAAAAAAAP////////////////4AAAAAAAAAAAAAAAAAAAAAAAD///4AAAAAAAAAAAAA///////////////////4AAAAA
AAAAAAAAAAAAAAAAAP///8AAAAAAAA/////////////////////////gAAAAAAAAAAAAAAAAAAAAB////+AAAAAA///////////////////////////4AAAA
AAAAAAAAAAAAAAAH//////gAAAAH///////////////////////////+AAAAAAAAAAAAAA////////////wAAAA/////////////////////////////gAAA
AAAAAAD///////////////+AAAH/////////////////////////////wAAAAAAAAB/////////////////4AA//////////////////////////////8AAA
AAAAA///////////////////wH///////////////////////////////AAAAAAAf////////////////////////////////////////////////////wAA
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
`.replace(/s+/g, "");

// Erst beim ersten Zugriff entpackt: das Modul wird auch auf dem Server
// geladen, dort wird die Maske nie gebraucht.
let bits: Uint8Array | null = null;

function mask(): Uint8Array {
  if (!bits) {
    const raw = atob(PACKED);
    bits = new Uint8Array(raw.length);
    for (let i = 0; i < raw.length; i++) bits[i] = raw.charCodeAt(i);
  }
  return bits;
}

function isLand(lat: number, lon: number): boolean {
  const column = ((Math.floor(lon + 180) % COLUMNS) + COLUMNS) % COLUMNS;
  const row = Math.min(ROWS - 1, Math.max(0, Math.floor(90 - lat)));
  const index = row * COLUMNS + column;
  return (mask()[index >> 3] & (128 >> (index & 7))) !== 0;
}

/** Was an einem Punkt der Kugel liegt. Die Reihenfolge ist die Betonung. */
export const Terrain = {
  Sea: 0,
  Land: 1,
  Europe: 2,
  Germany: 3,
} as const;

export type Terrain = (typeof Terrain)[keyof typeof Terrain];

type Outline = readonly (readonly [number, number])[];

/**
 * Europa als Fenster um die Landmasse: die Kanten laufen durchs Meer bzw.
 * durch dünn besiedelte Weiten, damit die Hervorhebung an den Küsten endet
 * und nicht als Rechteck über dem Kontinent liegt.
 */
const EUROPE: Outline = [
  [-11.0, 36.2], [-1.0, 36.2], [10.0, 37.2], [16.0, 37.2], [18.0, 34.6],
  [26.8, 34.6], [26.8, 41.5], [30.0, 44.6], [34.5, 46.4], [36.0, 50.5],
  [33.5, 56.0], [32.0, 62.0], [31.0, 66.5], [33.5, 71.5], [10.0, 72.0],
  [-5.0, 67.0], [-26.0, 67.5], [-26.0, 62.5], [-13.0, 59.0], [-11.0, 50.0],
];

/** Deutschland im Umriss — grob, aber mit Nordsee, Ostsee und Alpenrand. */
const GERMANY: Outline = [
  [7.0, 53.7], [8.6, 54.9], [11.0, 54.4], [13.8, 54.1], [14.6, 53.3],
  [14.7, 51.0], [12.1, 50.3], [13.4, 48.6], [12.9, 47.7], [10.2, 47.3],
  [7.6, 47.6], [8.2, 49.0], [6.4, 49.5], [6.0, 50.8], [6.2, 51.9],
  [7.0, 52.6], [7.2, 53.4],
];

/** Mitte Deutschlands — dort sitzt der Schein, der das Land hervorhebt. */
export const GERMANY_CENTER = { lat: 51.1, lon: 10.4 };

// Strahlensatz-Test (even-odd): zählt die Kanten links vom Punkt.
function inside(lat: number, lon: number, outline: Outline): boolean {
  let hit = false;
  for (let i = 0, j = outline.length - 1; i < outline.length; j = i++) {
    const [xi, yi] = outline[i];
    const [xj, yj] = outline[j];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
      hit = !hit;
    }
  }
  return hit;
}

/**
 * Kategorie eines Punktes. Teuer genug, dass die Komponente sie einmal je
 * Rasterpunkt vorberechnet und nicht pro Bild neu fragt.
 */
export function terrainAt(lat: number, lon: number): Terrain {
  if (!isLand(lat, lon)) return Terrain.Sea;
  if (inside(lat, lon, GERMANY)) return Terrain.Germany;
  if (inside(lat, lon, EUROPE)) return Terrain.Europe;
  return Terrain.Land;
}
